---
- name: copy files
  hosts: server1
  become: yes
  vars:
    source_folder: "/var/lib/jenkins/workspace/copy-files-pipeline/"
    destination_folder: "/home/anantlaghane/Documents"
  tasks:
    - name: Copy all files from Git to target server
      copy:
        src: "{{ source_folder }}"
        dest: "{{ destination_folder }}"
