---
- name: Copy selected files to target server
  hosts: server1
  become: yes
  vars:
    source_folder: "/var/lib/jenkins/workspace/copy-files-pipeline"
    destination_folder: "/home/anantlaghane/github_files"  
    selected_files: []

  tasks:
    - name: Copy selected files to remote server
      copy:
        src: "{{ source_folder }}/{{ item }}"
        dest: "{{ destination_folder }}/"
      with_items: "{{ selected_files }}"
