---
- name: copy files 
  hosts: server1
  become: yes
  vars:
    source_folder: "/home/anantlaghane/github_files"
    destination_folder: "/home/anantlaghane/github_files"
    selected_files: []
      

  tasks:
    - name: Copy selected files to target server
      copy:
        src: "{{ source_folder }}/{{ item }}"
        dest: "{{ destination_folder }}//{{ item }}"
      with_items: "{{ selected_files }}"

